[programs.localnet]
token_bonding_curve = "TBCwReYDDw8SvwVVKJHgatzeXKrLHnaTPyDGwkUoBsq"

[programs.mainnet]
token_bonding_curve = "TBCwReYDDw8SvwVVKJHgatzeXKrLHnaTPyDGwkUoBsq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/ts-mocha/bin/ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# `anchor test` looks for a specific hardcoded script called "test" (and anchor-cli::start_test_validator isn't publicly
# callable outside of `anchor test`), so just comment/uncomment this as needed for debugger
# test = "./node_modules/ts-mocha/bin/ts-mocha --inspect-brk -p ./tsconfig.json -t 1000000 tests/**/*.ts"
